const data = [
    {
        firstName: "דוד",
        lastName: "כהן",
        gender: "זכר",
        age: "23",
        city: "בני ברק",
        countryBirth: "",
        headdress: "מטפחת",
        pictue: "",
        SectoralAssociation: "הכהכג",
        bodyStracture: "רזה וגבוה",
        yeshivaOrSeminar: "כהגד",
        doingToday: "כהג",
        clothingStyle: "גגגגגכה",
        economicSituation: "כה",
        bodyStructure: "הכהגדדדדדדדדדדדדדדדדדדדד",
        healthCondition: "בריא",
        height: "1.73",
        look: "כגהגד",
        commitMoney: "הכג",
        requireMoney: "כהדגד",
        origin: "כהכגד",
        sector: "כה",
        colorSkin: "",
        clothingStyle: "",
        economicSituation: "",
        bornDate: "12/02/1999",
        familyStatus: "רווק",
        characters: "יראת שמיים וצנועה",
        email: "ertyui",
        phone: "0527163238",
        fatherName: "",
        fatherDoing: "דכהדגכ",
        motherName: "כגדה",
        motherDoing: "דדדדדדדכה",
        mozaAv: "כגדהגדדד",
        mozaEm: "כגהגכ",
        siblings: "דכג",
        parentStatus: "דגהגכ",
        halachaMethod: "הכד",
        drishotSector: "כהגד",
        drishotLook: "כגדה",
        drishotCharacters: "",
        drishotFavoriteMoza: "הרררר",
        drishotNotMoza: "בהגכדה",
        fromAge: "20",
        mostAge: "25",
        fromHeight: "הר1.ה",
        mostHeight: "1.6",
        casherPhone: "רה",
        licence: "הר",
        smoking: "ר",
        fillQuestionarieName: "ממלא",
        fillQuestionariePhone: "חליי",
        fillQuestionarieRelative: "הכה",
        recomendedPeople: [{
            recommendName: "ממליץ א",
            recommendPhone: "ממליץ א",
            recommendRelative: "ממליץ א"
        },
        {
            recommendName: "ממליץ בא",
            recommendPhone: "ממליץ בבא",
            recommendRelative: "ממליץ בבבבבא"
        },
        {
            recommendName: "ממליץ גגגא",
            recommendPhone: "ממליץ גגא",
            recommendRelative: "ממליץ גגא"
        }
        ],
        inLaws: [
            {
                fatherInLawName: "מחותן א",
                fatherInLawCity: "מחותן א",
                fatherInLawPhone: "מחותן א"
            },
            {
                fatherInLawName: "מחותן בא",
                fatherInLawCity: "מחותן בא",
                fatherInLawPhone: "מחותן בא"
            },
            {
                fatherInLawName: "מחותן גא",
                fatherInLawCity: "מחותן גא",
                fatherInLawPhone: "מחותן גא"
            }
        ]
    },
    {
        firstName: "שרה",
        lastName: "אלחרר",
        gender: "נקבה",
        age: "27",
        city: "אלעד",
        countryBirth: "",
        headdress: "מטפחת",
        pictue: "",
        SectoralAssociation: "הכהכג",
        bodyStracture: "רזה וגבוה",
        yeshivaOrSeminar: "כהגד",
        doingToday: "כהג",
        clothingStyle: "גגגגגכה",
        economicSituation: "כה",
        bodyStructure: "הכהגדדדדדדדדדדדדדדדדדדדד",
        healthCondition: "בריא",
        height: "1.73",
        look: "כגהגד",
        commitMoney: "הכג",
        requireMoney: "כהדגד",
        origin: "כהכגד",
        sector: "כה",
        colorSkin: "",
        clothingStyle: "",
        economicSituation: "",
        bornDate: "12/02/1999",
        familyStatus: "רווק",
        characters: "יראת שמיים וצנועה",
        email: "ertyui",
        phone: "0527163238",
        fatherName: "",
        fatherDoing: "דכהדגכ",
        motherName: "כגדה",
        motherDoing: "דדדדדדדכה",
        mozaAv: "כגדהגדדד",
        mozaEm: "כגהגכ",
        siblings: "דכג",
        parentStatus: "דגהגכ",
        halachaMethod: "הכד",
        drishotSector: "כהגד",
        drishotLook: "כגדה",
        drishotCharacters: "",
        drishotFavoriteMoza: "הרררר",
        drishotNotMoza: "בהגכדה",
        fromAge: "20",
        mostAge: "25",
        fromHeight: "הר1.ה",
        mostHeight: "1.6",
        casherPhone: "רה",
        licence: "הר",
        smoking: "ר",
        fillQuestionarieName: "ממלא",
        fillQuestionariePhone: "חליי",
        fillQuestionarieRelative: "הכה",
        recomendedPeople: [{
            recommendName: "ממליץ א",
            recommendPhone: "ממליץ א",
            recommendRelative: "ממליץ א"
        }
        ],
        inLaws: [
            {
                fatherInLawName: "מחותן א",
                fatherInLawCity: "מחותן א",
                fatherInLawPhone: "מחותן א"
            }
        ]
    },
    {
        firstName: "יעל",
        lastName: "משולמי",
        gender: "נקבה",
        age: "18",
        city: "בני ברק",
        countryBirth: "",
        headdress: "מטפחת",
        pictue: "",
        SectoralAssociation: "הכהכג",
        bodyStracture: "רזה וגבוה",
        yeshivaOrSeminar: "כהגד",
        doingToday: "כהג",
        clothingStyle: "גגגגגכה",
        economicSituation: "כה",
        bodyStructure: "הכהגדדדדדדדדדדדדדדדדדדדד",
        healthCondition: "בריא",
        height: "1.73",
        look: "כגהגד",
        commitMoney: "הכג",
        requireMoney: "כהדגד",
        origin: "כהכגד",
        sector: "כה",
        colorSkin: "",
        clothingStyle: "",
        economicSituation: "",
        bornDate: "12/02/1999",
        familyStatus: "רווק",
        characters: "יראת שמיים וצנועה",
        email: "ertyui",
        phone: "0527163238",
        fatherName: "",
        fatherDoing: "דכהדגכ",
        motherName: "כגדה",
        motherDoing: "דדדדדדדכה",
        mozaAv: "כגדהגדדד",
        mozaEm: "כגהגכ",
        siblings: "דכג",
        parentStatus: "דגהגכ",
        halachaMethod: "הכד",
        drishotSector: "כהגד",
        drishotLook: "כגדה",
        drishotCharacters: "",
        drishotFavoriteMoza: "הרררר",
        drishotNotMoza: "בהגכדה",
        fromAge: "20",
        mostAge: "25",
        fromHeight: "הר1.ה",
        mostHeight: "1.6",
        casherPhone: "רה",
        licence: "הר",
        smoking: "ר",
        fillQuestionarieName: "ממלא",
        fillQuestionariePhone: "חליי",
        fillQuestionarieRelative: "הכה",
        recomendedPeople: [{
            recommendName: "ממליץ א",
            recommendPhone: "ממליץ א",
            recommendRelative: "ממליץ א"
        }
        ],
        inLaws: [
            {
                fatherInLawName: "מחותן א",
                fatherInLawCity: "מחותן א",
                fatherInLawPhone: "מחותן א"
            }
        ]
    },
    {
        firstName: "חיים",
        lastName: "אלחרזי",
        gender: "זכר",
        age: "28",
        city: "אופקים",
        countryBirth: "",
        headdress: "מטפחת",
        pictue: "",
        SectoralAssociation: "הכהכג",
        bodyStracture: "רזה וגבוה",
        yeshivaOrSeminar: "כהגד",
        doingToday: "כהג",
        clothingStyle: "גגגגגכה",
        economicSituation: "כה",
        bodyStructure: "הכהגדדדדדדדדדדדדדדדדדדדד",
        healthCondition: "בריא",
        height: "1.73",
        look: "כגהגד",
        commitMoney: "הכג",
        requireMoney: "כהדגד",
        origin: "כהכגד",
        sector: "כה",
        colorSkin: "",
        clothingStyle: "",
        economicSituation: "",
        bornDate: "12/02/1999",
        familyStatus: "רווק",
        characters: "יראת שמיים וצנועה",
        email: "ertyui",
        phone: "0527163238",
        fatherName: "",
        fatherDoing: "דכהדגכ",
        motherName: "כגדה",
        motherDoing: "דדדדדדדכה",
        mozaAv: "כגדהגדדד",
        mozaEm: "כגהגכ",
        siblings: "דכג",
        parentStatus: "דגהגכ",
        halachaMethod: "הכד",
        drishotSector: "כהגד",
        drishotLook: "כגדה",
        drishotCharacters: "",
        drishotFavoriteMoza: "הרררר",
        drishotNotMoza: "בהגכדה",
        fromAge: "20",
        mostAge: "25",
        fromHeight: "הר1.ה",
        mostHeight: "1.6",
        casherPhone: "רה",
        licence: "הר",
        smoking: "ר",
        fillQuestionarieName: "ממלא",
        fillQuestionariePhone: "חליי",
        fillQuestionarieRelative: "הכה",
        recomendedPeople: [{
            recommendName: "ממליץ א",
            recommendPhone: "ממליץ א",
            recommendRelative: "ממליץ א"
        }
        ],
        inLaws: [
            {
                fatherInLawName: "מחותן א",
                fatherInLawCity: "מחותן א",
                fatherInLawPhone: "מחותן א"
            }
        ]
    },
]
export default data;
