export const DELETE_CANDIDATE = "DELETE_CANDIDATE";
export const ADD_CANDIDATE = "ADD_CANDIDATE";
export const LOAD_MEORASIM = "LOAD_MEORASIM";
export const CLOSE_MATCH = "CLOSE_MATCH";


export default {
    DELETE_CANDIDATE,
    ADD_CANDIDATE,
    LOAD_MEORASIM,
    CLOSE_MATCH
}