[
    { label: 'First Name', name: 'firstName', type: 'text' },
    { label: 'Last Name', name: 'lastName', type: 'text' },
    { label: 'Age', name: 'age', type: 'number' },
    { label: 'Marital Status', name: 'status', type: 'text' },
    { label: 'Date of Birth', name: 'bornDate', type: 'date' },
    { label: 'Country of Birth', name: 'countryBirth', type: 'text' },
    { label: 'City', name: 'city', type: 'text' },
    { label: 'Phone Number', name: 'phone', type: 'number' },
    { label: 'Character Traits', name: 'characters', type: 'text' },
    { label: 'Skin Color', name: 'colorSkin', type: 'text' },
    { label: 'Height', name: 'height', type: 'text' },
    { label: 'Body Structure', name: 'bodyStracture', type: 'text' },
    { label: 'Health Condition', name: 'healthCondition', type: 'text' },
    { label: 'Economic Condition', name: 'economicCondition', type: 'text' },
    { label: 'Clothing Style', name: 'clothingStyle', type: 'text' },
    { label: 'General Appearance', name: 'look', type: 'text' },
    { label: 'Head Covering', name: 'headdress', type: 'text' },
    { label: 'Sector', name: 'sector', type: 'text' },
    { label: 'Picture', name: 'picture', type: 'text' },
    { label: 'Financial Requirements', name: 'requireMoney', type: 'text' },
    { label: 'Financial Commitments', name: 'commitMoney', type: 'text' },
    { label: 'Seminar Name', name: 'seminar', type: 'text' },
    { label: 'Current Occupation', name: 'doingToday', type: 'text' },
    { label: "Father's Name", name: 'fatherName', type: 'text' },
    { label: "Mother's Name", name: 'motherName', type: 'text' },
    { label: "Father's Occupation", name: 'fatherDoing', type: 'text' },
    { label: "Mother's Occupation", name: 'motherDoing', type: 'text' },
    { label: "Father's Origin", name: 'mozaAv', type: 'text' },
    { label: "Mother's Origin", name: 'mozaEm', type: 'text' },
    { label: 'Number of Siblings', name: 'siblings', type: 'number' },
    { label: 'Halachic Method', name: 'halachaMethod', type: 'text' },
    { label: 'Requirements - Sector', name: 'drishotSector', type: 'text' },
    { label: 'Requirements - General Appearance', name: 'drishotLook', type: 'text' },
    { label: 'Requirements - Character Traits', name: 'drishotCharacters', type: 'text' },
    { label: 'Requirements - Preferred Origin', name: 'drishotFavoriteMoza', type: 'text' },
    { label: 'Requirements - Not of Origin', name: 'drishot', type:'text'},
    { label: 'drishotNotMoza', name: 'drNotMoza', type: 'text' },
    { label: 'fromAge', name: 'frAge', type: 'text' },
    { label: 'mostAge', name: 'moAge', type: 'text' },
    { label: 'fromHigh', name: 'frHigh', type: 'text' },
    { label: 'mostHigh', name: 'moHigh', type: 'text' },
    { label: 'casherPhone', name: 'cashPhone', type: 'checkbox' },
    { label: 'licence', name: 'rishayon', type: 'checkbox' }

]
   