const data = [
{
    firstName: "דוד",
    lastName: "כהן",
    age: "23",
    city: "בני ברק",
    headDress: "מטפחת",
    religiousBackground: "חרדי",
    placeOfStudy: "מאור התלמוד",
    financialRequirement: "2000000",
    financialCommitment: "400000",
    pictue: "",
    SectoralAssociation: "",
    generalLook: "רזה וגבוה",
    clothingStyle: "",
    economicSituation: "",
    bodyStructure: "",
    healthCondition: "בריא",
    height: "1.73",
    skinTone: "כהה",
    bornDate: "12/02/1999",
    familyStatus: "רווק",
    characteristics: "יראת שמיים וצנועה",
    telephone:"0527163238"
},
{
    firstName: "יוסף",
    lastName: "חיים",
    age: "21",
    city: "ירושלים",
    headDress: "פאה",
    religiousBackground: "חרדי",
    placeOfStudy: "רשבי",
    financialRequirement: "2000000",
    financialCommitment: "400000",
    pictue: "",
    SectoralAssociation: "",
    generalLook: "רזה וגבוה",
    clothingStyle: "",
    economicSituation: "",
    bodyStructure: "",
    healthCondition: "בריא",
    height: "1.73",
    skinTone: "כהה",
    bornDate: "12/02/1999",
    familyStatus: "רווק",
    characteristics: "יראת שמיים וצנועה",
    telephone:"0527163238"
},
{
    firstName: "רינת",
    lastName: "אלחדד",
    age: "28",
    city: "אופקים",
    headDress: "פאה",
    religiousBackground: "דתי",
    placeOfStudy: "סמינר אופקים",
    financialRequirement: "",
    financialCommitment: "400000",
    pictue: "",
    SectoralAssociation: "",
    generalLook: "שמנמנה",
    clothingStyle: "",
    economicSituation: "",
    bodyStructure: "",
    healthCondition: "בריא",
    height: "1.6",
    skinTone: "כהה",
    bornDate: "12/02/1999",
    familyStatus: "הרווק",
    characteristics: "יראת שמיים וצנועה",
    telephone:"0527163238"
}
]
export default data;
